const prose = {
  color: '#3d3020', fontSize: 14, lineHeight: 1.8, marginBottom: 16,
};
const h2 = {
  color: '#2c2416', fontSize: 16, fontWeight: 700, margin: '28px 0 8px',
};

export function PrivacyPolicy({ onBack }) {
  return (
    <div className="fade-in" style={{ maxWidth: 680, margin: '0 auto', paddingBottom: 60 }}>
      <button onClick={onBack} style={{ background: 'none', border: 'none', color: '#9c8b6e', fontSize: 14, cursor: 'pointer', padding: '16px 0', display: 'block' }}>
        ← Back
      </button>
      <h1 style={{ color: '#2c2416', fontSize: 26, fontWeight: 700, marginBottom: 6 }}>Privacy Policy</h1>
      <p style={{ color: '#9c8b6e', fontSize: 13, marginBottom: 32 }}>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

      <p style={prose}>Camp With My Dog ("we," "us," or "our") is a camping trip planner for dog owners. We take your privacy seriously. This policy explains what data we collect and how we use it.</p>

      <h2 style={h2}>What we collect</h2>
      <p style={prose}><strong>Data you enter in the app</strong> — your starting location, vehicle, dog name and breed, trip preferences, and notes — is stored <em>only in your browser's local storage</em> on your own device. We do not transmit this to our servers or store it in any database.</p>
      <p style={prose}><strong>Trip planning requests</strong> — when you generate a trip plan, your preferences are sent to Anthropic's API to generate the recommendation. Anthropic's privacy policy governs that data. We do not store your trip requests on our servers beyond what's needed to generate the response.</p>
      <p style={prose}><strong>Analytics</strong> — we use GoatCounter, a privacy-friendly analytics tool, to count page views and events (like trips planned and saved). GoatCounter does not use cookies or track individual users. No personal information is collected. You can review GoatCounter's privacy policy at goatcounter.com.</p>
      <p style={prose}><strong>Shared trips</strong> — if you use the share feature, trip data is encoded directly in the URL. We do not store shared trips on our servers.</p>

      <h2 style={h2}>What we don't collect</h2>
      <p style={prose}>We do not collect your name, email address, phone number, or payment information. We do not create user accounts. We do not use advertising cookies or tracking pixels. We do not sell data to third parties.</p>

      <h2 style={h2}>Third-party services</h2>
      <p style={prose}>The app uses the following third-party services: Anthropic (AI trip generation), Open-Meteo (weather data, no account required), GoatCounter (analytics), and Google Maps (directions links). Each service's own privacy policy applies to their portion of the experience.</p>

      <h2 style={h2}>Data deletion</h2>
      <p style={prose}>Since your data lives in your browser, you can delete it at any time by going to your profile and tapping "Clear profile," or by clearing your browser's local storage for this site. This immediately removes all saved trips, your profile, and preferences.</p>

      <h2 style={h2}>Contact</h2>
      <p style={prose}>Questions? Reach us at <a href="mailto:hello@campwithmydog.com" style={{ color: '#5c7a3e' }}>hello@campwithmydog.com</a>.</p>
    </div>
  );
}

export function TermsOfService({ onBack }) {
  return (
    <div className="fade-in" style={{ maxWidth: 680, margin: '0 auto', paddingBottom: 60 }}>
      <button onClick={onBack} style={{ background: 'none', border: 'none', color: '#9c8b6e', fontSize: 14, cursor: 'pointer', padding: '16px 0', display: 'block' }}>
        ← Back
      </button>
      <h1 style={{ color: '#2c2416', fontSize: 26, fontWeight: 700, marginBottom: 6 }}>Terms of Service</h1>
      <p style={{ color: '#9c8b6e', fontSize: 13, marginBottom: 32 }}>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

      <p style={prose}>By using Camp With My Dog ("the app"), you agree to these terms. If you don't agree, please don't use the app.</p>

      <h2 style={h2}>What the app does</h2>
      <p style={prose}>Camp With My Dog generates AI-powered camping trip suggestions based on the information you provide. Trip recommendations are for informational purposes only. Always verify current road conditions, fire restrictions, campsite availability, and regulations before your trip.</p>

      <h2 style={h2}>No guarantees</h2>
      <p style={prose}>Trip suggestions are generated by an AI and may contain errors, outdated information, or inaccuracies. We do not guarantee that any suggested campsite is accessible, available, or appropriate for your vehicle or dog. Conditions in the outdoors change — always check with the relevant agency (US Forest Service, BLM, state parks) before heading out.</p>
      <p style={prose}><strong>You are solely responsible for your own safety and the safety of your dog when camping.</strong> The app's dog heat warnings, weather forecasts, and safety briefings are informational aids, not professional safety advice.</p>

      <h2 style={h2}>Acceptable use</h2>
      <p style={prose}>You agree not to: use the app to generate excessive API requests (automated or manual), attempt to circumvent rate limits, or use the service in any way that could harm other users or the availability of the service.</p>

      <h2 style={h2}>Intellectual property</h2>
      <p style={prose}>The app's code, design, and branding belong to Camp With My Dog. Trip plans generated by the AI are yours to use freely.</p>

      <h2 style={h2}>Limitation of liability</h2>
      <p style={prose}>Camp With My Dog is provided "as is" without warranty of any kind. We are not liable for any damages resulting from your use of the app, including but not limited to vehicle damage, personal injury, or lost/cancelled trips based on app recommendations.</p>

      <h2 style={h2}>Changes</h2>
      <p style={prose}>We may update these terms occasionally. Continued use of the app after changes means you accept the updated terms.</p>

      <h2 style={h2}>Contact</h2>
      <p style={prose}>Questions? Reach us at <a href="mailto:hello@campwithmydog.com" style={{ color: '#5c7a3e' }}>hello@campwithmydog.com</a>.</p>
    </div>
  );
}
